/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link.js";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>news</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <a className="text-4xl text-white">
          <Link href="/eng">en</Link>
        </a>
        <a className="text-4xl text-white">
          <Link href="/pl">pl</Link>
        </a>
        <a className="text-4xl text-white">working on the ui</a>
      </main>
    </>
  );
};

export default Home;
