/* eslint-disable @next/next/no-img-element */
import axios from "axios";
import { type NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import { useEffect, useState } from "react";
import { env } from "../env/client.mjs";
const Home: NextPage = () => {
  const apikey = env.NEXT_PUBLIC_KEY;
  const url = `https://newsapi.org/v2/everything?q=bbc-news&language=en&sortBy=publishedAt&apiKey=${apikey}`;
  const [articles, setArticles] = useState([
    {
      title: "example",
      author: "example",
      description: "example",
      publishedAt: "example",
      source: {
        id: "example",
        name: "example",
      },
      url: "https://example.com",
      urlToImage: "https://example.com",
    },
  ]);
  useEffect(() => {
    const getArticles = async () => {
      const res = await axios.get(url);
      setArticles(res.data.articles);
    };
    getArticles();
    console.log(articles);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className=" grid grid-cols-4 p-4">
          {articles.map((article, index) => {
            let { title, description } = article;
            if (title === "example") return;
            if (title.length > 50) title = title.substring(0, 50) + "...";
            if (description.length > 170)
              description = description.substring(0, 170) + "...";
            return (
              <div
                key={index}
                className="h-72 w-60 rounded border-2 border-black bg-white"
              >
                <h1>{article.title.substring(0, 50)}</h1>
                <p>{article.description.substring(0, 50)}</p>
                <img src={article.urlToImage} width={200} height={200} alt="" />
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
};

export default Home;
